on:
  schedule:
    - cron: '0 0 * * *'
name: Update Generated Data
jobs:
  update-generated-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.BOOSTPORT_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.BOOSTPORT_AUTOMATION_APP_PRIVATE_KEY }}
      - name: Set environment variables from .env
        uses: xom9ikk/dotenv@v2.3.0
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Generate types
        env:
          CYBER_TIPLINE_USERNAME: ${{ secrets.CYBER_TIPLINE_USERNAME }}
          CYBER_TIPLINE_PASSWORD: ${{ secrets.CYBER_TIPLINE_PASSWORD }}
        run: go generate ./...
      - name: Open PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: update-generated-types
          author: GitHub <noreply@github.com>
          committer: GitHub <noreply@github.com>
          commit-message: Update generated types
          title: 'Update generated types'
          body: |
            Automated update for:
            - `cybertipline/generate/cyber_tipline.xsd`
            - `cybertipline/types.go`
          labels: automated pr
          team-reviewers: open-source
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1